purge_keep_days: 7
purge_interval: 1

exclude:
  domains:
    - zwave
    - camera
    - sun
  entities:
    - switch.skybell_front_door_do_not_disturb
    - sensor.home_energy_meter_energy_3
    - sensor.home_energy_meter_previous_reading
    - sensor.home_energy_meter_current
    - sensor.home_energy_meter_voltage
    - sensor.home_energy_meter_power
    - sensor.aeotec_zw095_home_energy_meter_gen5_previous_reading
